### ISSUE TITLE
min SDK 16 problem

### ISSUE THREAD

**Issue by shahkarraza001** [nabinbhandari/Android-Permissions#10]
for min sdk 16 it does't show the permissoins dialog. i dont know why. but it works for 15 and the previous ones.

**Comment by nabinbhandari** [comment]
Which device are you running your app? The permissions are requested in the run-time only for devices with API level 23 or above.

If you mean it doesn't work for the case of app with min SDK 16, but device's API level >= 23, please provide me with sample code/project to reproduce it.
