### ISSUE TITLE
Any way to center the text of the dialog?

### ISSUE THREAD

**Issue by Bots** [nabinbhandari/Android-Permissions#14]
The dialog that pops up with the rationale looks kind of funny on my device. Is there any way to center that text? I can't seem to find the xml.

**Comment by nabinbhandari** [comment]
For now, the only option is to clone the repository and use the module 'permissions' directly in your app so that you can edit the source code.

After that, you can edit the method `showRationale()` of the class `PermissionsActivity` to show a dialog of your choice.
