### ISSUE TITLE
Is it possible to call and get permission callbacks in Fragment?

### ISSUE THREAD

**Issue by isabsent** [nabinbhandari/Android-Permissions#15]
There is an opportunity to call permission request right from the `Fragment`:

    void requestPermissions(@NonNull String[] permissions, int requestCode)
and get a result in the same `Fragment`:

    onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults)
in [android.support.v4.app.Fragment](https://developer.android.com/reference/android/support/v4/app/Fragment.html#onRequestPermissionsResult(int,%20java.lang.String[],%20int[])). Does your library allow this too?

**Comment by nabinbhandari** [comment]
You don't need to use `onRequestPermissionsResult` to get the result. You can simply pass the context using the method `getContext()` of `Fragment` and get the callback directly in the parameter of type `PermissionHandler` in the `check` method.
