### ISSUE TITLE
One time i check "Set Not to ask again", it always show setting dialog

### ISSUE THREAD

**Issue by arifaizin** [nabinbhandari/Android-Permissions#19]
it is weird, but i fell when i check, "set not to ask again" for permission"WRITE_EXTERNAL_STORAGE", its likely saved in project, so when i want to call it again in another phone, it still show setting dialog, and i cannot get "WRITE_EXTERNAL_STORAGE" permission in every phone

**Comment by nabinbhandari** [comment]
What do you mean by "in another phone"? The user behavior for one device can never affect the app in another device. Please explain your problem in more details or provide sample code to reproduce the problem in other devices. 
Also note that the library also shows the settings dialog when the permission has not been declared in the manifest. Please check for that too.
