### ISSUE TITLE
Options when checking for single permission

### ISSUE THREAD

**Issue by soenkegissel** [nabinbhandari/Android-Permissions#21]
Hi,
I was suffering of issue #11 and fixed it by using setCreateNewTask().
But I can surely not be the only one calling the check from a fragment in example. 
In IMHO the option is hidden to deep and is not well documented enough.

But my mayor issue is that check function only supports Options parameter in combination with String[] not with String. Can you change that? Of course I can use String[] permissions = {single permission}

**Comment by nabinbhandari** [comment]
Please stick with `String[] permissions = {single_permission}` for now.
