### ISSUE TITLE
Multiple permissions not working

### ISSUE THREAD

**Issue by sunbyte** [nabinbhandari/Android-Permissions#6]
Hi, this library don't work for me.
Can't ask for multiple permissions at the same time.
It asks only for the first one in the array.
I'm trying to allow both the READ and WRITE storage permissions at once, but without any success.

**Comment by nabinbhandari** [comment]
Hello, if you request and get the permission for `WRITE_EXTERNAL_STORAGE`, the permission `READ_EXTERNAL_STORAGE` will automatically be granted. If you have further issue, please include an example code which causes the problem.

**Comment by sunbyte** [comment]
I need WRITE_EXTERNAL_STORAGE permission to download a remote file and READ_EXTERNAL_STORAGE to give the user an option to open the downloaded file. When WRITE_EXTERNAL_STORAGE is allowed by the user, the download process start and the file is downloaded successful. But when I try to open the file, the app crashes. 

Here is the code for opening file from storage (works perfect if the READ_EXTERNAL_STORAGE is allowed): [https://pastebin.com/jZZvqjJw](https://pastebin.com/jZZvqjJw)

**Comment by nabinbhandari** [comment]
I am unable to test your code because it lacks definitions of some methods. However. I did a simple write and read operation on a file and it is working fine.

Please test the following code in your device:

**Manifest:**

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

**MainActivity:**

    String[] permissions = {Manifest.permission.WRITE_EXTERNAL_STORAGE,
            Manifest.permission.READ_EXTERNAL_STORAGE};
    Permissions.check(this, permissions, null, null, new PermissionHandler() {
        @Override
        public void onGranted() {
            try {
                File root = Environment.getExternalStorageDirectory();
                File testFile = new File(root, "test.txt");

                FileOutputStream out = new FileOutputStream(testFile);
                out.write("Hello World".getBytes());
                out.close();

                FileInputStream in = new FileInputStream(testFile);
                byte[] data = new byte[11];
                in.read(data);
                in.close();

                String message = "Read: " + new String(data);
                Toast.makeText(MainActivity.this, message, Toast.LENGTH_SHORT).show();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    });

Note that you can simply just request `WRITE_EXTERNAL_STORAGE` only and it should work fine.
